# Generated by Django 4.2 on 2025-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoDraw',
            fields=[
                ('round_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('draw_date', models.DateField()),
                ('winning_numbers', models.CharField(max_length=50)),
                ('bonus_number', models.IntegerField()),
            ],
        ),
    ]
